version: "3.4"

services:
  social_network_api:
    image: ${DOCKER_REGISTRY}network_api
    build:
      context: .
      dockerfile: src/Systems/SocialNetwork.WebAPI/Dockerfile
    env_file:
      - env.api
    depends_on:
      - social_network_pgsl
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  social_network_identity:
    image: ${DOCKER_REGISTRY}network_identity
    build:
      context: .
      dockerfile: src/Systems/SocialNetwork.IdentityServer/Dockerfile
    depends_on:
      - social_network_pgsl
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  social_network_pgsl:
    image: postgres
    
  social_network_redis:
    image: redis
