version: "3.4"

services:
  social_network_api:
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    env_file:
      - env.api
    depends_on:
      - social_network_pgsl
    networks:
      - shared_soc_net
  
  social_network_identity:
    ports:
      - "7000:80"
    env_file:
      - env.identity
    depends_on:
      - social_network_pgsl
    networks:
      - shared_soc_net
  
  social_network_pgsl:
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
    networks:
      - shared_soc_net
        
  social_network_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_soc_net
    volumes:
      - ~/.docker-conf/redis/data/:/data
      
  social_network_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    networks:
      - shared_soc_net
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
        
  social_network_worker:
    networks:
      - shared_soc_net
    env_file:
      - env.worker

networks:
  shared_soc_net:
    name: soc_net 
    driver: bridge